# This file is used for local compose overrides only.  It must be fed into docker compsose manually via
# docker compose -f docker-compose.yml -f compose.local.yml [command]
# If troubleshooting the service bus stuff, you can set the SERVICE_BUS_CONNECTION_STRING to the correct op secrete, and the call the above command with op run -- docker compose etc;  This will inject the op secret into the compose file.
# debugpy is a flag that changes the pipeline entrypoint script to call main.py with debugpy and the proper debugpy port exposed. It'll stop the program and wait for you to attach to it (likely using the .vscode launch config Python Debugger Pipeline).  Feel free to toggle the flag if you're just wanting to do some log debugging or don't need it.
#
version: "3.8"
services:
  pipeline:
    platform: linux/x86_64
    build:
      context: ../fetcher-pipeline
      # args:
      #   debugpy: true
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      # "op://AppDev Scripture Accessibility/languageapi-bus-send-connstring/dev/conn_string"
      SERVICE_BUS_CONNECTION_STRING: "noop"
    volumes:
      - ../fetcher-pipeline/content_local:/content
