version: "3.8"
services:
  fileserver:
    build: ./fileserver
    ports:
      - "8081:80"
    volumes:
      - fetcher-content:/srv/content
      - fetcher-rc:/srv/rc
    restart: unless-stopped
  fetcher-app:
  # for local development, tag your image with "local" e.g. `docker build -t bibletranslationtools/fetcher:local .`
    image: bibletranslationtools/fetcher:${FETCHER_IMAGE_TAG}
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      CDN_BASE_URL: ${CDN_BASE_URL}
      CDN_BASE_RC_URL: ${CDN_BASE_RC_URL}
      RC_TEMP_DIR: ${RC_TEMP_DIR}
      CACHE_REFRESH_MINUTES: ${CACHE_REFRESH_MINUTES}
    volumes:
      - fetcher-content:/content
      - fetcher-rc:${RC_TEMP_DIR}
      - fetcher-repos:${ORATURE_REPO_DIR}
    restart: unless-stopped
  ftp:
    image: bogem/ftp
    volumes:
      - fetcher-content:/home/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    environment:
      FTP_USER: ${fetcher_ftp_user}
      FTP_PASS: ${fetcher_ftp_pass}
      PASV_ADDRESS: ${fetcher_ftp_ip}
    restart: always
  pipeline:
    image: bibletranslationtools/fetcher-pipeline:${FETCHER_IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SENTRY_DSN: ${SENTRY_DSN}
      PM2_PUBLIC_KEY: ${PM2_PUBLIC_KEY}
      PM2_SECRET_KEY: ${PM2_SECRET_KEY}
      RC_TEMP_DIR: ${RC_TEMP_DIR}
      ORATURE_REPO_DIR: ${ORATURE_REPO_DIR}
    volumes:
      - fetcher-content:/content
      - fetcher-rc:${RC_TEMP_DIR}
      - fetcher-repos:${ORATURE_REPO_DIR}

volumes:
  fetcher-content:
  fetcher-rc:
  fetcher-repos:
