version: "3.8"
services:
  fileserver:
    build: ./fileserver
    ports:
      - "8081:80"
    volumes:
      - "${SRV_FILES_DIR}:/srv/files"
  fetcher-app:
    image: bibletranslationtools/fetcher
    ports:
      - "8080:8080"
    env_file:
      - vars.env
    environment:
      - CDN_BASE_URL=http://localhost:8081
      - GATEWAY_LANG_FILE=/srv/resources/languages.csv
    volumes:
      - ./build/libs/bible-translation-tools_fetcher.jar:/app/fetcher.jar
      - ./resources:/srv/resources
      - ./file.csv:/srv/file.csv
      - "${SRV_FILES_DIR}:/where/ktor/expects/files"
