version: "3.8"
services:
  fileserver:
    build: ./fileserver
    ports:
      - "8081:80"
    volumes:
      - fetcher-content:/srv/files
  fetcher-app:
    image: bibletranslationtools/fetcher
    ports:
      - "8080:8080"
    env_file:
      - vars.env
    volumes:
      - fetcher-content:/content
  ftp:
    image: bogem/ftp
    volumes:
      - fetcher-content:/home/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    environment:
      FTP_USER: ${fetcher_ftp_user}
      FTP_PASS: ${fetcher_ftp_pass}
      PASV_ADDRESS: '127.0.0.1'

volumes:
  fetcher-content:
