version: "3.8"
services:
  fileserver:
    build: ./fileserver
    ports:
      - "8081:80"
    env_file:
      - vars.env
    volumes:
      - "${SRV_FILES_DIR}:/srv/files"
  fetcher-app:
    image: bibletranslationtools/fetcher
    ports:
      - "8080:8080"
    env_file:
      - vars.env
    volumes:
      - ../build/libs/bible-translation-tools_fetcher.jar:/app/fetcher.jar
      - ./resources:/srv/resources
      - /home/dj/source_content:/content
